### ISSUE TITLE
对大神项目的一点想法

### ISSUE THREAD

**Issue by hanchanpo13** [LevisLv/statistics#1]
我最近也在做全埋点方案，对比了神策开源，和您的代码，发现您的代码结构比神策清晰，但是支持的范围稍微比较窄 比如 dialog、TabHost、tablayout等，建议您可以看下神策思路，另外非常乐意参与此插件项目开发

**Comment by hanchanpo13** [comment]
https://github.com/sensorsdata/sa-sdk-android-plugin2

**Comment by LevisLv** [comment]
> 我最近也在做全埋点方案，对比了神策开源，和您的代码，发现您的代码结构比神策清晰，但是支持的范围稍微比较窄 比如 dialog、TabHost、tablayout等，建议您可以看下神策思路，另外非常乐意参与此插件项目开发

很荣幸收到你的赞美和建议，也非常欢迎你参与此开源项目的开发维护。
